name: Build and Publish Github Packages

on:
  push:
     branches:
        - main
        - dev

jobs:
  build-and-publish-head:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.5.0

    - name: Build and publish to Github using git-tag
      uses: pmorelli92/github-container-registry-build-push@2.0.0
      with:
        github-token: ${{ secrets.TOKEN }}
        image-name: TEST
        extract-git-tag: true
        dockerfile: Dockerfile